version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672" # amqp
            - "15672:15672" # management
        networks:
            - "example-network"
    mailcatcher: # https://mailcatcher.me
        image: schickling/mailcatcher
        ports:
            - "1080:1080" # web client
            - "1025:1025" # SMTP
        networks:
            - "example-network"
    redis:
        image: redis
        ports:
            - "6378:6379"
        networks:
            - "example-network"
networks:
    example-network:
        driver: bridge