version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/ # rabbitmq.conf
            - ./rabbitmq/data/:/var/lib/rabbitmq/ # data
            - ./rabbitmq/logs/:/var/log/rabbitmq/ # logs
        ports:
            - 5672:5672 # amqp
            - 15672:15672 # management
        networks:
            - example-network

    # https://mailcatcher.me
    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080 # web client
            - 1025:1025 # SMTP
        networks:
            - example-network

    redis:
        image: redis
        command: redis-server --include /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/etc/:/usr/local/etc/redis/ # config
        ports:
            - 6379:6379
        networks:
            - example-network

networks:
    example-network:
        driver: bridge
