version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "5672:5672" # amqp
            - "15672:15672" # management
        networks:
            - "example-network"
networks:
    example-network:
        driver: bridge