version: '3'
services:
    rabbitmq:
        build: ./images/rabbitmq
        hostname: my-rabbit
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - example-network

    # https://mailcatcher.me
    mailcatcher:
        image: schickling/mailcatcher:${MAILCATCHER_TAG}
        ports:
            - 1080:1080 # web client
            - 1025:1025 # SMTP
        networks:
            - example-network

    redis:
        image: redis:${REDIS_TAG}
        command: redis-server --include /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/etc/:/usr/local/etc/redis/ # config
        ports:
            - 6378:6379
        networks:
            - example-network

    mongodb-primary:
        image: 'bitnami/mongodb:4.4'
        ports:
            - 27017:27017
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
            - MONGODB_REPLICA_SET_MODE=primary
            - MONGODB_ROOT_PASSWORD=root
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        volumes:
            - 'mongodb_master_data:/bitnami'
        networks:
            - example-network

    mongodb-secondary:
        image: 'bitnami/mongodb:4.4'
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
            - MONGODB_REPLICA_SET_MODE=secondary
            - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
            - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
            - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        networks:
            - example-network

    mongodb-arbiter:
        image: 'bitnami/mongodb:4.4'
        depends_on:
            - mongodb-primary
        environment:
            - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
            - MONGODB_REPLICA_SET_MODE=arbiter
            - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
            - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
            - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=root
            - MONGODB_REPLICA_SET_KEY=replicasetkey123
        networks:
            - example-network

networks:
    example-network:
        driver: bridge

volumes:
    mongodb_master_data:
        driver: local
