version: '3'
services:
    rabbitmq:
        image: rabbitmq:${RABBITMQ_TAG}
        volumes:
            - ./rabbitmq/etc/:/etc/rabbitmq/ # rabbitmq.conf
            - ./rabbitmq/data/:/var/lib/rabbitmq/ # data
            - ./rabbitmq/logs/:/var/log/rabbitmq/ # logs
        ports:
            - 5672:5672 # amqp
            - 15672:15672 # management
        networks:
            - example-network

    # https://mailcatcher.me
    mailcatcher:
        image: schickling/mailcatcher:${MAILCATCHER_TAG}
        ports:
            - 1080:1080 # web client
            - 1025:1025 # SMTP
        networks:
            - example-network

    redis:
        image: redis:${REDIS_TAG}
        command: redis-server --include /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/etc/:/usr/local/etc/redis/ # config
        ports:
            - 6378:6379
        networks:
            - example-network

    mongo:
        image: mongo:${MONGO_TAG}
        volumes:
            - ./mongo/data/:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        networks:
            - example-network

    mongo-express:
        image: mongo-express:${MONGO_EXPRESS_TAG}
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
            ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
        depends_on:
          - mongo
        networks:
            - example-network

networks:
    example-network:
        driver: bridge
