version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80" # http
            - "443:443" # https
        volumes:
            - ./hosts:/etc/nginx/conf.d # nginx hosts config
            - ./www:/var/www # projects root
            - ./logs:/var/log/nginx # nginx logs
        networks:
            - example-network
    php:
        build: ./images/php
        volumes:
            - ./www:/var/www # projects root
        networks:
            - example-network
    mysql:
        image: mysql:5
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - example-network
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_DATABASE: default
            MYSQL_PASSWORD: password
networks:
    example-network:
        driver: bridge
